### ISSUE TITLE
Use caching in the Angular site to avoid redundant requests [polish]

### ISSUE THREAD

**Issue by javeit** [revaturelabs/cms-meta#10]

**Comment by carolynrehm** [comment]
@javeit this can be marked as a bug, and can be focused on in future sprints after features have been completed and the focus moves to optimization

**Comment by josephhighe** [comment]
Added ngx-cacheable package which allows for use of Cachable and CachableBuster and GlobaleCacheBusterNotifier annotations. These allow for caching and caching removal when data has been manipulated.
