### ISSUE TITLE
Set Up Environments for Angular App

### ISSUE THREAD

**Issue by carolynrehm** [revaturelabs/cms-meta#13]
Currently, [the URL for HTTP requests](https://github.com/revaturelabs/cms-angular/blob/dev/cms-force/src/app/constants/endpoints.service.ts#L8) are being hard coded into the application's services. This baseUrl value should be handled in the app's [environments](https://github.com/revaturelabs/cms-angular/tree/dev/cms-force/src/environments).

----------------------------------------------
Problem has been resolved URL is now in Environment.

**Comment by DustinMartin95** [comment]
@cloud-ops, is there currently a url for the HTTP requests that I should set the production url to?

**Comment by Quinn-Donnelly** [comment]
@DustinMartin95 
Use the following for now this will eventually have a Route53 dns entry once they are done but this is the URL of the ALB. The applicaiton isn't currently setup behind it but it will be by COB.
**URL:** cms-dev-1861735057.us-east-1.elb.amazonaws.com
