### ISSUE TITLE
Parameterize Services with Enviroment Variables 

### ISSUE THREAD

**Issue by carolynrehm** [revaturelabs/cms-meta#14]
Hard coded URL's and credentials should be removed. This includes values such as `spring.datasource.url`, `spring.datasource.username`, and `spring.datasource.password` in the [content-service application.yml](https://github.com/revaturelabs/cms-content-service/blob/dev/src/main/resources/application.yml), and `eureka.client.service-url.defaultZone` in both the content-service and gateway-service

The necessary environment variables should then be documented as a part of the startup documentation [here](https://github.com/revaturelabs/cms-meta/wiki/Startup-Documentation)

**Comment by carolynrehm** [comment]
URL: cms-dev-1861735057.us-east-1.elb.amazonaws.com as found in #13

**Comment by josephhighe** [comment]
verified the hard coded values in spring.datasource.url, spring.datasource.username, and spring.datasource.password are no longer present, and the default zone in content-service as well as gateway service are properly accounted for. Within gateway-service, it is no longer present. Within content-service it has been refactored to http://localhost:8761/eureka/
