### ISSUE TITLE
Creation of Config Server

### ISSUE THREAD

**Issue by carolynrehm** [revaturelabs/cms-meta#15]
Create a configuration server using Spring Cloud Config to centralize configuration management.

The repository for the server can be found [here](https://github.com/revaturelabs/cms-config). 

The repository for the configuration can be found [here](https://github.com/revaturelabs/cms-config-server).

**Comment by carolynrehm** [comment]
Make sure these repos follow the same branching structure as the others in this project. They will also have to be added to the meta repo

**Comment by DustinMartin95** [comment]
@Quinn-Donnelly You talked about profiles on Friday, do you have any more information on what profiles are needed for the config server and also if there is any other configurations you want set up for the config server.

**Comment by Quinn-Donnelly** [comment]
Have the default profile set information such as port number (and other things that are true across envs, application name ect.) Then configure a local, dev, and prod profile for now leave dev and prod empty @revaturelabs/cloud-ops team will handle filling that out. I will likely commit their values they send to me. For local set values for local development.
